-- CreateEnum
CREATE TYPE "ColorTallo" AS ENUM ('VERDE', 'AZUL', 'NARANJA', 'AMARILLO', 'ROJO');

-- AlterTable
ALTER TABLE "Rabanoide" ADD COLUMN     "autocombustion" DECIMAL(65,30) NOT NULL DEFAULT 0.5,
ADD COLUMN     "colortallo" "ColorTallo" NOT NULL DEFAULT 'VERDE',
ADD COLUMN     "damage" DECIMAL(65,30) NOT NULL DEFAULT 0.5,
ADD COLUMN     "defensa" DECIMAL(65,30) NOT NULL DEFAULT 0.5,
ADD COLUMN     "hiperactividad" DECIMAL(65,30) NOT NULL DEFAULT 0.5,
ADD COLUMN     "inteligencia" DECIMAL(65,30) NOT NULL DEFAULT 0.5,
ADD COLUMN     "regeneracion" DECIMAL(65,30) NOT NULL DEFAULT 0.5,
ADD COLUMN     "saltoaltura" DECIMAL(65,30) NOT NULL DEFAULT 0.5,
ADD COLUMN     "velocidad" DECIMAL(65,30) NOT NULL DEFAULT 0.5;
